name: Generate csv

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main

jobs:
  run-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "src/requirements.txt"
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: run python file
        run: |
             python3 src/fuelish.py
             cd src
             ls
             git config --global user.name "Bot"
             git config --global user.email "your email"
             git clean  -d  -f
             git pull
             git add -A
             git commit -m "Data-"$NOW
             git push
